apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
  namespace: buy-better

spec:
  selector:
    matchLabels:
      app: core-api
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: core-api
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: core-api
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resource.cpuRequest }}
            limits:
              cpu: {{ .Values.resource.cpuLimit }}
          ports:
            - name: core-api-port
              containerPort: 3030

          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 3030
            initialDelaySeconds: {{ .Values.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.livenessPeriodSeconds }}
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4

          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 3030
            initialDelaySeconds: {{ .Values.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.readinessPeriodSeconds }}
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: WEB_SERVICE_ENV
              value: {{ .Values.env.webService }}
            - name: DB_DSN # dev local db is not sensitive
              value: {{ .Values.env.dbDSN }}
            - name: PRODUCT_SERVICE_ADDR
              value: {{ .Values.env.prodServiceAddr }}
            - name: GOOGLE_CALLBACK
              value: {{ .Values.env.googleCallback }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.env.jaegerEndpoint }}
            - name: TOKEN_ENCODED
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: TOKEN_ENCODED
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: SESSION_SECRET
