---
# Source: bb-core-api-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
  namespace: buy-better

spec:
  selector:
    matchLabels:
      app: core-api
  replicas: 1
  template:
    metadata:
      labels:
        app: core-api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: core-api
          image: opplieam/bb-core-api:0.0.1-4288a88
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 500m
          ports:
            - name: core-api-port
              containerPort: 3030

          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 3030
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4

          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: WEB_SERVICE_ENV
              value: cluster-dev
            - name: DB_DSN # dev local db is not sensitive
              value: postgresql://postgres:admin1234@host.minikube.internal:5433/buy-better-core?sslmode=disable
            - name: PRODUCT_SERVICE_ADDR
              value: product-server-service.buy-better.svc.cluster.local:3031
            - name: GOOGLE_CALLBACK
              value: http://127.0.0.1:3030/v1/auth/google/callback
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://host.minikube.internal:14268/api/traces
            - name: TOKEN_ENCODED
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: TOKEN_ENCODED
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: SESSION_SECRET
