---
# Source: bb-product-server-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server-deployment
  namespace: buy-better

spec:
  selector:
    matchLabels:
      app: product-server
  replicas: 1
  template:
    metadata:
      labels:
        app: product-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: product-server
          image: opplieam/bb-product-server:0.0.1-a5fb256
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 500m
          ports:
            - name: product-port
              containerPort: 3031

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: WEB_SERVICE_ENV
              value: cluster-dev
            - name: DB_DSN # dev local db is not sensitive
              value: postgresql://postgres:admin1234@host.minikube.internal:5433/buy-better-core?sslmode=disable
            - name: DB_DRIVER
              value: "postgres"
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://host.minikube.internal:14268/api/traces
