apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bb-core-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opplieam/bb-k8s-infra/
    targetRevision: HEAD
    path: bb-core-api
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: buy-better
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true